### ISSUE TITLE
invalid dnsname⁩

### ISSUE THREAD

**Issue by ILoveCoding1100** [ankicommunity/anki-sync-server-rs#25]
It works fine with ssl_enable=false. But if it switch to ssl_enable=true I get "invalid dnsname"
I'm using a self sign certificate: 
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 3650 -nodes

**Steps to reproduce:**

Environment: Kubuntu 20.04

1. Extracted anki
ankisyncd-0.1.3-linux.tar.gz

2. added cert.pm and key.pem and adapted Settings.toml 
```

[address]
host="127.0.0.1"
port = "27701"
# use current executable path ,only set filename
[paths]
# set root_dir as working dir where server data(collections folder) and database(auth.db...) reside
root_dir="."
#following three lines are unnessesary and can be skipped
 data_root = ""
 auth_db_path = ""
 session_db_path = ""
        
# user will be added 
#into auth.db if not empty,and two fields must not be empty
[account]
username="Test"
password="Test123"
        
# embeded encrypted http /https credential if in Intranet
# true to enable ssl or false
[localcert]
ssl_enable=true
cert_file="cert.pem"
key_file="key.pem"

```

Started anki:
/ankisyncd 
[2022-03-19T21:38:11Z INFO  actix_server::builder] Starting 24 workers
[2022-03-19T21:38:11Z INFO  actix_server::builder] Starting "actix-web-service-127.0.0.1:27701" service on 127.0.0.1:27701

3. Tried to connect but got the following message:
Please check your internet connection.
Error details: ⁨error sending request for url (): error trying to connect: invalid dnsname⁩

![image](https://user-images.githubusercontent.com/57010389/159139499-48ceb6f9-1508-4462-92af-3cb1b2d60f86.png)

![image](https://user-images.githubusercontent.com/57010389/159139490-afcb1852-b5bf-4300-94ea-55ebb7297168.png)

![image](https://user-images.githubusercontent.com/57010389/159139549-952c77ce-ef89-42ad-be4c-874eef7f8eca.png)

**Comment by ILoveCoding1100** [comment]
The whole package with settings and certificate

[ankisyncd-linux.zip](https://github.com/ankicommunity/anki-sync-server-rs/files/8310195/ankisyncd-linux.zip)

**Comment by dobefore** [comment]
Thanks for using and detailed info.

It seems that you are using proxy?
you may change host field in Settings.toml to your local address (e.g.192.168.0.88)
Or retry after closing proxy

BTW,we recommand using [mkcert](https://github.com/FiloSottile/mkcert) ro manage certificate.

**Comment by ILoveCoding1100** [comment]
>> It seems that you are using proxy?
No, not at the moment.

>> curl https://127.0.0.1:27701
I tried this already. As far as I remember I got an certificate error. Something with: self sign certificate... 

>> you may change host field in Settings.toml to your local address (e.g.192.168.0.88)
Yes, I will try this. 

>> BTW,we recommand using [mkcert](https://github.com/FiloSottile/mkcert) ro manage certificate.
**Will this also work with my Android phone within my local network?**

**Comment by dobefore** [comment]
> Will this also work with my Android phone within my local network? Will it accept the certificate.

yes,it will.but rootCA certificate gemerated by mkcert  must be installed on Android.

> I tried this already. As far as I remember I got an certificate error. Something with: self sign certificate...

I guess you may not import rootca to system trusted store

**Comment by redmie** [comment]
I second @dobefore on this.

I also think the problem comes from the anki client side as it is the one that does the certificate verification (the server just provides the one you give). When using self signed certs you must add your root of trust certificate to the system certificate key-store for it to be recognized as valid by the system. This will work on android with the ankidroid app for sure. On desktop I have no idea if anki consults the system root of trust key-store or not, as such I cannot say (but the answer is somewhere in the anki source code for sure :wink:).

Personally if I want the thing easily accessible far and wide I use letsencrypt to have valid certificate. If restricted to my personal use/internal network i just setup a local vpn such as wireguard between the client and the host to avoid snooping and keep the client/server connection unencrypted. tl;dr I bypass the certificate problem as it is often a mess and the way things are handled is not consistent between apps.

**Comment by dobefore** [comment]
I guess issue should be fixed following instructions above..But feel free to reopen
